### ISSUE TITLE
Enable CORS support

### ISSUE THREAD

**Issue by fcoralsasso** [bento-platform/bento_drs#19]
This error was raised while fetching data from a DRS instance on Dashboard V2

![image](https://user-images.githubusercontent.com/60624699/90806609-174aa980-e2d2-11ea-89b3-e5b4eb4474b8.png)

For now, we are using this extension:
https://flask-cors.readthedocs.io/en/latest/

**Comment by davidlougheed** [comment]
I waffle on this a bit but in some ways I feel like CORS headers are out-of-scope for a microservice and should be handled at the proxy level instead...

**Comment by haoyuanli** [comment]
Yeah, I agree; I guess this is more of an issue for development; since in production once it's handled at the proxy level it will be a non-issue. There's a workaround to deal with it during the development process by using extensions like this though https://chrome.google.com/webstore/detail/cross-domain-cors/mjhpgnbimicffchbodmgfnemoghjakai

**Comment by davidlougheed** [comment]
We could add a flag to enable flask-cors with some kind of env var if useful

**Comment by haoyuanli** [comment]
Sure! If it's not too much extra work. Thanks
